# Generated by Django 4.2 on 2026-01-18 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_unblockrequest_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_1', models.CharField(max_length=15)),
                ('emergency_contact_2', models.CharField(blank=True, max_length=15)),
                ('family_contact', models.CharField(max_length=15)),
                ('consent_given', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
