# Generated by Django 4.2 on 2026-01-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emergencyincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='safety_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='safety_consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
