# Generated by Django 4.2 on 2026-01-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_farmerprofile_safety_consent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='emergency_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='last_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
